// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var StringHelpers$ReactTemplate = require("./StringHelpers.bs.js");

var component = ReasonReact.reducerComponent("Example");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", undefined, React.createElement("section", {
                              className: "hero is-primary"
                            }, React.createElement("div", {
                                  className: "hero-body"
                                }, React.createElement("div", {
                                      className: "container"
                                    }, React.createElement("h1", {
                                          className: "title"
                                        }, "Meeting Minutes"), React.createElement("h2", {
                                          className: "subtitle"
                                        }, "Generate markdown")))), React.createElement("div", {
                              className: "container is-fluid"
                            }, React.createElement("div", {
                                  className: "columns"
                                }, React.createElement("div", {
                                      className: "column"
                                    }, React.createElement("label", {
                                          className: "label"
                                        }, "Title"), React.createElement("input", {
                                          className: "input",
                                          placeholder: "Title",
                                          type: "text",
                                          value: self[/* state */1][/* title */0],
                                          onChange: (function ($$event) {
                                              return Curry._1(self[/* send */3], /* Title */Block.__(0, [$$event.target.value]));
                                            })
                                        })), React.createElement("div", {
                                      className: "column"
                                    }, React.createElement("label", {
                                          className: "label"
                                        }, "URL"), React.createElement("input", {
                                          className: "input",
                                          placeholder: "URL",
                                          type: "text",
                                          value: self[/* state */1][/* url */1],
                                          onChange: (function ($$event) {
                                              return Curry._1(self[/* send */3], /* Url */Block.__(1, [$$event.target.value]));
                                            })
                                        }))), React.createElement("code", undefined, StringHelpers$ReactTemplate.createTitle(self[/* state */1][/* title */0], self[/* state */1][/* url */1]))));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* title */"",
                      /* url */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* title */state[/* title */0],
                            /* url */action[0]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* title */action[0],
                            /* url */state[/* url */1]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
