// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE


var anchor = (
    function (title) {
      return '#' + title.trim().toLowerCase().replace(/[^\w\- ]+/g, '').replace(/\s/g, '-').replace(/\-+$/, '');
    }
);

export {
  anchor ,
  
}
/* anchor Not a pure module */
