// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Component$ReactTemplate from "./Component.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component$ReactTemplate.make(/* array */[])), "app");

export {
  
}
/*  Not a pure module */
