// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var anchor = (
    function (title) {
      return '#' + title.trim().toLowerCase().replace(/[^\w\- ]+/g, '').replace(/\s/g, '-').replace(/\-+$/, '');
    }
);

var urlToIssueNumber = (
    function (url) {
      return url.replace(/\D/g,'');
    }
  );

exports.anchor = anchor;
exports.urlToIssueNumber = urlToIssueNumber;
/* anchor Not a pure module */
